# nc_console.py — CLI for NeuroConsole (NC)
# Usage:
#   nc <file.nc>
#   nc <https://site/path/file.nc>
#   nc --learn
#   nc --learn basics
# Options:
#   --base <path_or_url_dir>
#   --libs <path> (repeatable)
#   --allow-http
#   --allow-private

from __future__ import annotations

import os
import sys
import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path

# ------------------------------------------------------------
# UTF-8 FIX (Windows + QProcess / ncw):
# Prevent: "charmap codec can't encode characters ..."
# Must be BEFORE importing nc (because nc/prints may happen early)
# ------------------------------------------------------------
os.environ.setdefault("PYTHONIOENCODING", "utf-8")
os.environ.setdefault("PYTHONUTF8", "1")
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

from urllib.parse import urlparse  # (kept, even if not used)

import nc as nc


def is_url(s: str) -> bool:
    return s.startswith("https://") or s.startswith("http://")


def resolve_local_target(target: str) -> str:
    """Resolve a relative NC file from the shell, then from NC's install folder."""
    if is_url(target) or os.path.isabs(target):
        return target
    candidates = [Path.cwd() / target, Path(__file__).resolve().parent / target]
    if not target.lower().endswith((".nc", ".nce")):
        candidates.extend([
            Path.cwd() / (target + ".nc"),
            Path.cwd() / (target + ".nce"),
            Path(__file__).resolve().parent / (target + ".nc"),
            Path(__file__).resolve().parent / (target + ".nce"),
        ])
    for candidate in candidates:
        if candidate.is_file():
            return str(candidate.resolve())
    return target


def read_text_from_target(target: str, policy: nc.NCPolicy) -> str:
    if is_url(target):
        return nc._fetch_url_text(target, policy)
    if target.lower().endswith(".nce"):
        text, _base, _source = nc.nce_read_entry_text(target, policy=policy)
        return text
    # local file
    with open(target, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def compute_base(target: str) -> str:
    if is_url(target):
        # base = url directory
        return target.rsplit("/", 1)[0] + "/"
    # local file directory
    return os.path.dirname(os.path.abspath(target)) or os.getcwd()


def _safe_exe_name_from_target(target: str) -> str:
    base = os.path.basename(target)
    if base.lower().endswith(".nc"):
        base = base[:-3]
    if base.lower().endswith(".nce"):
        base = base[:-4]
    base = base.strip() or "nc_app"
    cleaned = []
    for ch in base:
        cleaned.append(ch if (ch.isalnum() or ch in ("_", "-", ".")) else "_")
    return "".join(cleaned).strip("._") or "nc_app"


def _existing_search_paths(paths: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for raw in paths or []:
        try:
            p = os.path.abspath(str(raw))
        except Exception:
            continue
        if not os.path.isdir(p):
            continue
        key = os.path.normcase(p)
        if key in seen:
            continue
        seen.add(key)
        out.append(p)
    return out


def build_exe_from_nc(target: str, policy: nc.NCPolicy, base: str, search_paths: list[str], enable_ui: bool = True) -> str:
    if is_url(target):
        raise RuntimeError("--exe currently supports local .nc/.nce files only.")

    src_path = os.path.abspath(target)
    if not os.path.isfile(src_path):
        raise FileNotFoundError(src_path)

    exe_name = _safe_exe_name_from_target(src_path)
    pyinstaller_exe = shutil.which("pyinstaller")
    pyinstaller_cmd = [pyinstaller_exe] if pyinstaller_exe else [sys.executable, "-m", "PyInstaller"]

    build_root = Path(base if (base and not is_url(base)) else os.path.dirname(src_path)).resolve()
    output_root = build_root / "nc_exe_build"
    output_root.mkdir(parents=True, exist_ok=True)
    data_separator = ";" if os.name == "nt" else ":"

    safe_search_paths = _existing_search_paths(search_paths)
    hidden_imports = [
        "nc_diagnostics",
        "nc_runtime_support",
        "nc_module_registry",
        "nc_ui_app",
        "nc_physics2d",
        "nc_physics2d_app",
        "nc_physics3d",
        "nc_physics3d_app",
        "json",
        "urllib.request",
        "urllib.parse",
        "decimal",
        "tokenize",
        "dataclasses",
        "typing",
        "ipaddress",
        "hmac",
        "hashlib",
        "secrets",
        "socket",
        "random",
        "math",
        "re",
        "io",
        "ast",
        "zlib",
        "tarfile",
        "getpass",
        "cryptography",
        "cryptography.hazmat.primitives.ciphers.aead",
        "cryptography.hazmat.primitives.kdf.pbkdf2",
    ]

    launcher_code = f"""# Auto-generated by nc --exe
from __future__ import annotations
import os
import sys

# Preload stdlib modules BEFORE local search paths are injected.
# Bugfix: avoids broken frozen startup where stdlib resolution can be shadowed
# or missed too early in one-file builds.
import json  # noqa: F401
import urllib.request  # noqa: F401
import urllib.parse  # noqa: F401
import decimal  # noqa: F401
import tokenize  # noqa: F401
import dataclasses  # noqa: F401
import typing  # noqa: F401
import ipaddress  # noqa: F401
import hmac  # noqa: F401
import hashlib  # noqa: F401
import secrets  # noqa: F401
import socket  # noqa: F401
import random  # noqa: F401
import math  # noqa: F401
import re  # noqa: F401
import io  # noqa: F401
import ast  # noqa: F401
import zlib  # noqa: F401
import tarfile  # noqa: F401
import getpass  # noqa: F401

HERE = os.path.dirname(os.path.abspath(__file__))
if not {bool(enable_ui)!r}:
    os.environ["NC_DISABLE_GRAPHICS"] = "1"
PROGRAM_ROOT = os.path.join(HERE, "program")
SOURCE_PATH = os.path.join(PROGRAM_ROOT, {os.path.basename(src_path)!r})
EXTRA_PATHS = [PROGRAM_ROOT, os.path.join(PROGRAM_ROOT, "libs")]
for _p in list(EXTRA_PATHS):
    if _p and _p not in sys.path:
        sys.path.insert(0, _p)
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import nc as nc

def main() -> int:
    try:
        nc.run_file(
            SOURCE_PATH,
            policy=nc.NCPolicy(
                allow_http={bool(policy.allow_http)!r},
                allow_private_hosts={bool(policy.allow_private_hosts)!r},
                max_module_bytes={int(policy.max_module_bytes)!r},
                url_timeout_sec={int(policy.url_timeout_sec)!r},
                max_import_depth={int(policy.max_import_depth)!r},
                max_steps={int(policy.max_steps)!r},
                max_expr_len={int(policy.max_expr_len)!r},
                data_dir={policy.data_dir!r},
            ),
            enable_ui={bool(enable_ui)!r},
            extra_paths=EXTRA_PATHS,
        )
        return 0
    except Exception as e:
        print(nc.format_exception(e))
        return 1

if __name__ == "__main__":
    raise SystemExit(main())
"""

    with tempfile.TemporaryDirectory(prefix="nc_exe_") as tmp:
        launcher = Path(tmp) / f"{exe_name}_launcher.py"
        launcher.write_text(launcher_code, encoding="utf-8")

        cmd = pyinstaller_cmd + [
            "--noconfirm",
            "--clean",
            "--onefile",
            "--name", exe_name,
            "--distpath", str(output_root / "dist"),
            "--workpath", str(output_root / "build"),
            "--specpath", str(output_root / "spec"),
            "--add-data", f"{str(build_root)}{data_separator}program",
            "--add-data", f"{str(src_path)}{data_separator}program",
        ]
        for hidden in hidden_imports:
            cmd.extend(["--hidden-import", hidden])
        cmd.append(str(launcher))

        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            stderr = (proc.stderr or "").strip()
            stdout = (proc.stdout or "").strip()
            details = stderr or stdout or "PyInstaller failed"
            if "No module named PyInstaller" in details:
                raise RuntimeError("PyInstaller is not installed. Install it with: pip install pyinstaller") from None
            raise RuntimeError(details)

    executable_suffix = ".exe" if os.name == "nt" else ""
    exe_path = output_root / "dist" / f"{exe_name}{executable_suffix}"
    if not exe_path.is_file():
        raise RuntimeError(f"Build finished but EXE was not found: {exe_path}")
    return str(exe_path)


def package_macos_dmg(executable: str, output_root: Path, app_name: str) -> str:
    """Wrap a built NC executable in a minimal macOS .app and .dmg."""
    if sys.platform != "darwin":
        raise RuntimeError("--dmg is available only when NC is built on macOS.")
    hdiutil = shutil.which("hdiutil")
    if not hdiutil:
        raise RuntimeError("macOS hdiutil was not found; install or use the native macOS tools.")

    dmg_path = output_root / "dist" / f"{app_name}.dmg"
    with tempfile.TemporaryDirectory(prefix="nc_dmg_") as temporary:
        staging = Path(temporary) / app_name
        app_bundle = staging / f"{app_name}.app"
        binary_dir = app_bundle / "Contents" / "MacOS"
        binary_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(executable, binary_dir / app_name)
        (binary_dir / app_name).chmod(0o755)
        plist = app_bundle / "Contents" / "Info.plist"
        plist.write_text(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
            "<plist version=\"1.0\"><dict>\n"
            f"<key>CFBundleExecutable</key><string>{app_name}</string>\n"
            f"<key>CFBundleIdentifier</key><string>org.neuroconsole.{app_name}</string>\n"
            f"<key>CFBundleName</key><string>{app_name}</string>\n"
            "<key>CFBundlePackageType</key><string>APPL</string>\n"
            "<key>CFBundleVersion</key><string>1.2.0-alpha.2</string>\n"
            "</dict></plist>\n",
            encoding="utf-8",
        )
        proc = subprocess.run(
            [hdiutil, "create", "-volname", app_name, "-srcfolder", str(staging), "-ov", "-format", "UDZO", str(dmg_path)],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            raise RuntimeError((proc.stderr or proc.stdout or "hdiutil failed").strip())
    return str(dmg_path)


def package_linux_appimage(executable: str, output_root: Path, app_name: str) -> str:
    """Create a standard Linux AppImage using the optional appimagetool."""
    if not sys.platform.startswith("linux"):
        raise RuntimeError("--appimage is available only when NC is built on Linux.")
    appimagetool = shutil.which("appimagetool")
    if not appimagetool:
        raise RuntimeError("appimagetool was not found. Install appimagetool on Linux, then run --appimage again.")

    appdir = output_root / "appimage" / f"{app_name}.AppDir"
    usr_bin = appdir / "usr" / "bin"
    usr_bin.mkdir(parents=True, exist_ok=True)
    shutil.copy2(executable, usr_bin / app_name)
    (usr_bin / app_name).chmod(0o755)
    (appdir / "AppRun").write_text(
        "#!/bin/sh\nexec \"$(dirname \"$0\")/usr/bin/" + app_name + "\" \"$@\"\n",
        encoding="utf-8",
    )
    (appdir / "AppRun").chmod(0o755)
    (appdir / f"{app_name}.desktop").write_text(
        "[Desktop Entry]\nType=Application\n"
        f"Name={app_name}\nExec={app_name}\nTerminal=true\nCategories=Utility;\n",
        encoding="utf-8",
    )
    output_path = output_root / "dist" / f"{app_name}.AppImage"
    proc = subprocess.run([appimagetool, str(appdir), str(output_path)], capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError((proc.stderr or proc.stdout or "appimagetool failed").strip())
    return str(output_path)



def main(argv: list[str]) -> int:
    argv = list(argv or [])
    version_selector = f"--{nc.__version__}"
    if argv and str(argv[0]).lower() == version_selector.lower():
        argv = argv[1:]
    p = argparse.ArgumentParser(prog="nc", add_help=True)
    p.add_argument("--version", action="version", version=f"NC {nc.__version__}")
    p.add_argument("target", nargs="?", help="Path to .nc file or URL to .nc")
    p.add_argument("--learn", nargs="?", const="", help="Start learn mode (optional topic)")
    p.add_argument("--base", default=None, help="Base folder/URL for resolving relative imports")
    p.add_argument("--libs", action="append", default=[], help="Extra library search path (repeatable)")
    p.add_argument("--allow-http", action="store_true", help="Allow http:// imports (default: https only)")
    p.add_argument("--allow-private", action="store_true", help="Allow private/localhost URL imports (default blocked)")
    p.add_argument("--no-ui", action="store_true", help="Disable __TWIN__ UI output")
    p.add_argument("--no-log", action="store_true", help="Disable step logs")
    p.add_argument("--exe", action="store_true", help="Build the local .nc file into a standalone executable via PyInstaller")
    p.add_argument("--dmg", action="store_true", help="On macOS, also create a .dmg package")
    p.add_argument("--appimage", action="store_true", help="On Linux, also create an AppImage package")
    p.add_argument("--pack-nce", nargs=2, metavar=("SOURCE", "OUTPUT"), help="Create an encrypted .nce package from a .nc file or folder")
    p.add_argument("--nce-entry", default=None, help="Entrypoint inside the .nce package, for example main.nc")
    p.add_argument("--nce-password", default=None, help="Password for reading or creating .nce packages")

    args = p.parse_args(argv)

    # Learn mode
    if args.learn is not None:
        topic = args.learn.strip() or None
        nc.run_learn(topic)
        return 0

    if args.dmg and args.appimage:
        p.error("--dmg and --appimage cannot be used together")

    if not args.target:
        if not args.pack_nce:
            p.print_help()
            return 2

    policy = nc.NCPolicy(
        allow_http=bool(args.allow_http),
        allow_private_hosts=bool(args.allow_private),
    )
    if args.no_ui:
        os.environ["NC_DISABLE_GRAPHICS"] = "1"

    if args.nce_password:
        os.environ["NC_NCE_PASSWORD"] = str(args.nce_password)

    if args.pack_nce:
        src, out = args.pack_nce
        try:
            out_path = nc.create_nce(src, out, password=args.nce_password, entrypoint=args.nce_entry)
            print("NC NCE:", out_path)
            return 0
        except Exception as e:
            print(nc.format_exception(e), file=sys.stderr)
            return 1

    target = resolve_local_target(args.target)

    # Allow accidental URL/file fragments like "wormpad.nc#"
    target = target.split("#", 1)[0]

    # For local files: allow calling without .nc/.nce extension
    if (not is_url(target)) and (not target.lower().endswith((".nc", ".nce"))):
        if os.path.isfile(target + ".nc"):
            target = target + ".nc"
        elif os.path.isfile(target + ".nce"):
            target = target + ".nce"

    base = args.base or compute_base(target)

    search_paths = []
    # default search paths for local usage
    if not is_url(base):
        search_paths.extend([base, os.path.join(base, "libs")])
    # additional libs from args
    for lp in args.libs:
        search_paths.append(lp)

    try:
        if args.exe or args.dmg or args.appimage:
            exe_path = build_exe_from_nc(
                target=target,
                policy=policy,
                base=base,
                search_paths=search_paths,
                # ``nc --exe`` is the console converter. Its generated
                # executable must stay a console program, even when the NC
                # source contains a physics ``app.run()`` call.
                enable_ui=False,
            )
            if args.dmg:
                print("NC DMG:", package_macos_dmg(exe_path, Path(exe_path).parents[1], _safe_exe_name_from_target(target)))
            elif args.appimage:
                print("NC APPIMAGE:", package_linux_appimage(exe_path, Path(exe_path).parents[1], _safe_exe_name_from_target(target)))
            else:
                print("NC EXE:", exe_path)
            return 0

        if is_url(target):
            text = read_text_from_target(target, policy)
            if args.no_log:
                text = text + "\n\n# __NC_CONSOLE_NO_LOG__\n"
            nc.run_text(
                text,
                base=base,
                extra_paths=search_paths,
                policy=policy,
                enable_ui=(not args.no_ui),
                source_name=target,
            )
        elif target.lower().endswith(".nce"):
            nc.run_file(target, policy=policy, enable_ui=(not args.no_ui), extra_paths=search_paths)
        else:
            text = read_text_from_target(target, policy)
            if args.no_log:
                text = text + "\n\n# __NC_CONSOLE_NO_LOG__\n"
            nc.run_text(
                text,
                base=base,
                extra_paths=search_paths,
                policy=policy,
                enable_ui=(not args.no_ui),
                source_name=os.path.abspath(target),
            )
        return 0
    except Exception as e:
        print(nc.format_exception(e), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
